import React from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { useLanguage } from '@/context/LanguageContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';
import { Phone, Shield, Ambulance, Flame, AlertTriangle, Heart, Baby, MapPin } from 'lucide-react';
import { mockEmergencyContacts } from '@/utils/mockData';
import { supabase } from '@/integrations/supabase/client';

const EmergencyContacts: React.FC = () => {
  const { translate, language } = useLanguage();
  const { toast } = useToast();

  const getLocalizedText = (eng: string, hindi: string, marathi: string) => {
    if (language === 'english') return eng;
    if (language === 'hindi') return hindi;
    return marathi;
  };

  const pageTitle = getLocalizedText(
    "Emergency Contacts",
    "आपातकालीन संपर्क",
    "आपत्कालीन संपर्क"
  );

  const createEmergencyAlert = async (contact: any, locationData?: { latitude: number; longitude: number; locationName?: string }) => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        toast({
          title: getLocalizedText("Authentication Required", "प्रमाणीकरण आवश्यक", "प्रमाणीकरण आवश्यक"),
          description: getLocalizedText(
            "Please log in to use emergency services",
            "आपातकालीन सेवाओं का उपयोग करने के लिए लॉग इन करें",
            "आपत्कालीन सेवा वापरण्यासाठी लॉगिन करा"
          ),
          variant: "destructive",
        });
        return;
      }

      // Get user profile for name and phone
      const { data: profile } = await supabase
        .from('profiles')
        .select('full_name, phone_number')
        .eq('id', user.id)
        .single();

      const alertData = {
        alert_id: '', // Will be auto-generated by trigger
        user_id: user.id,
        name: profile?.full_name || 'Anonymous User',
        phone_number: profile?.phone_number || 'Not provided',
        type: contact.type,
        location_name: locationData?.locationName || 'Location not available',
        latitude: locationData?.latitude || null,
        longitude: locationData?.longitude || null,
        message: getLocalizedText(
          `Emergency call placed to ${contact.name}`,
          `${contact.name} को आपातकालीन कॉल किया गया`,
          `${contact.name} ला आपत्कालीन कॉल केला`
        ),
        status: 'Active'
      };

      const { data, error } = await supabase
        .from('emergency_alerts')
        .insert(alertData)
        .select()
        .single();

      if (error) {
        console.error('Error creating alert:', error);
        throw error;
      }

      console.log('Emergency alert created:', data);
      
      toast({
        title: getLocalizedText("Emergency Alert Created", "आपातकालीन अलर्ट बनाया गया", "आपत्कालीन अलर्ट तयार केले"),
        description: getLocalizedText(
          `Alert ${data.alert_id} has been sent to authorities`,
          `अलर्ट ${data.alert_id} अधिकारियों को भेजा गया है`,
          `अलर्ट ${data.alert_id} अधिकाऱ्यांना पाठवले आहे`
        ),
      });

    } catch (error) {
      console.error('Error creating emergency alert:', error);
      toast({
        title: getLocalizedText("Alert Error", "अलर्ट त्रुटि", "अलर्ट त्रुटी"),
        description: getLocalizedText(
          "Failed to create emergency alert",
          "आपातकालीन अलर्ट बनाने में विफल",
          "आपत्कालीन अलर्ट तयार करण्यात अयशस्वी"
        ),
        variant: "destructive",
      });
    }
  };

  const shareLocationAndCall = async (phoneNumber: string, name: string, contact: any) => {
    try {
      // Get current location
      const position = await new Promise<GeolocationPosition>((resolve, reject) => {
        navigator.geolocation.getCurrentPosition(resolve, reject, {
          enableHighAccuracy: true,
          timeout: 10000,
          maximumAge: 0
        });
      });

      const { latitude, longitude } = position.coords;
      const locationUrl = `https://maps.google.com/maps?q=${latitude},${longitude}`;
      
      // Create emergency alert in database
      await createEmergencyAlert(contact, {
        latitude,
        longitude,
        locationName: `Location: ${latitude.toFixed(6)}, ${longitude.toFixed(6)}`
      });
      
      // Create SMS with location
      const message = encodeURIComponent(`EMERGENCY: I need help! My current location is: ${locationUrl}`);
      const smsUrl = `sms:${phoneNumber}?body=${message}`;
      
      // Send SMS with location first
      window.open(smsUrl, '_blank');
      
      // Small delay then initiate call
      setTimeout(() => {
        const telUrl = `tel:${phoneNumber}`;
        window.location.href = telUrl;
      }, 1000);

      toast({
        title: getLocalizedText("Emergency Call Initiated", "आपातकालीन कॉल शुरू", "आपत्कालीन कॉल सुरू"),
        description: getLocalizedText(
          `Calling ${name} and emergency alert created`,
          `${name} को कॉल कर रहे हैं और आपातकालीन अलर्ट बनाया गया`,
          `${name} ला कॉल करत आहे आणि आपत्कालीन अलर्ट तयार केले`
        ),
        duration: 3000,
      });
    } catch (error) {
      console.error('Location error:', error);
      
      // If location fails, still create alert and make call
      await createEmergencyAlert(contact);
      
      const telUrl = `tel:${phoneNumber}`;
      window.location.href = telUrl;
      
      toast({
        title: getLocalizedText("Calling", "कॉल कर रहे हैं", "कॉल करत आहे"),
        description: getLocalizedText(
          `Calling ${name} (Location sharing failed)`,
          `${name} को कॉल कर रहे हैं (स्थान साझाकरण असफल)`,
          `${name} ला कॉल करत आहे (स्थान शेअरिंग अयशस्वी)`
        ),
        variant: "destructive",
        duration: 3000,
      });
    }
  };

  const getEmergencyIcon = (type: string) => {
    switch(type) {
      case 'police':
        return <Shield className="h-8 w-8 text-blue-600" />;
      case 'ambulance':
        return <Ambulance className="h-8 w-8 text-red-600" />;
      case 'fire':
        return <Flame className="h-8 w-8 text-orange-600" />;
      case 'disaster':
        return <AlertTriangle className="h-8 w-8 text-yellow-600" />;
      case 'women':
        return <Heart className="h-8 w-8 text-pink-600" />;
      case 'child':
        return <Baby className="h-8 w-8 text-green-600" />;
      default:
        return <Phone className="h-8 w-8 text-gray-600" />;
    }
  };

  return (
    <DashboardLayout title={pageTitle}>
      <Card className="max-w-3xl mx-auto">
        <CardHeader>
          <CardTitle>{pageTitle}</CardTitle>
          <CardDescription>
            {getLocalizedText(
              "Important emergency contact numbers that might be helpful during your pilgrimage",
              "तीर्थयात्रा के दौरान सहायक हो सकने वाले महत्वपूर्ण आपातकालीन संपर्क नंबर",
              "तीर्थयात्रेदरम्यान उपयुक्त ठरू शकणारे महत्त्वाचे आपत्कालीन संपर्क क्रमांक"
            )}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {mockEmergencyContacts.map((contact) => (
              <Card key={contact.id} className="border-l-4 border-l-pilgrim-orange">
                <div className="flex p-4 items-center">
                  <div className="mr-4">
                    {getEmergencyIcon(contact.type)}
                  </div>
                  <div className="flex-grow">
                    <h3 className="font-semibold text-lg">{contact.name}</h3>
                    <p className="text-xl font-bold text-pilgrim-orange">{contact.phoneNumber}</p>
                  </div>
                  <Button 
                    variant="default" 
                    size="sm" 
                    className="bg-pilgrim-orange hover:bg-orange-600"
                    onClick={() => shareLocationAndCall(contact.phoneNumber, contact.name, contact)}
                  >
                    <Phone className="h-4 w-4 mr-1" />
                    {getLocalizedText("Call", "कॉल", "कॉल")}
                  </Button>
                </div>
              </Card>
            ))}
          </div>
          
          <div className="mt-8 bg-red-50 p-4 rounded-md border border-red-200">
            <h3 className="font-bold text-red-700 flex items-center">
              <AlertTriangle className="h-5 w-5 mr-2" />
              {getLocalizedText(
                "SOS Emergency",
                "SOS आपातकाल",
                "SOS आपत्कालीन"
              )}
            </h3>
            <p className="mt-2 text-red-700 flex items-center">
              <MapPin className="h-4 w-4 mr-2" />
              {getLocalizedText(
                "In case of a life-threatening emergency, press the SOS button in the bottom right corner. It will automatically share your location and call emergency services.",
                "जान के खतरे वाली आपात स्थिति में, दाएं कोने में SOS बटन दबाएं। यह स्वचालित रूप से आपका स्थान साझा करेगा और आपातकालीन सेवाओं को कॉल करेगा।",
                "जीवघेण्या आपत्कालीन स्थितीत, खाली उजव्या कोपऱ्यातील SOS बटन दाबा. हे आपोआप तुमचे स्थान शेअर करेल आणि आपत्कालीन सेवांना कॉल करेल."
              )}
            </p>
          </div>
        </CardContent>
      </Card>
    </DashboardLayout>
  );
};

export default EmergencyContacts;
