import React from 'react';
import { PhoneCall } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';
import { useLanguage } from '@/context/LanguageContext';
import { mockEmergencyContacts } from '@/utils/mockData';
import { supabase } from '@/integrations/supabase/client';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

const SosButton = () => {
  const { toast } = useToast();
  const { language } = useLanguage();

  const getLocalizedText = (eng: string, hindi: string, marathi: string) => {
    if (language === 'english') return eng;
    if (language === 'hindi') return hindi;
    return marathi;
  };

  const createEmergencyAlert = async (contact: any, locationData?: { latitude: number; longitude: number; locationName?: string }) => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        toast({
          title: getLocalizedText("Authentication Required", "प्रमाणीकरण आवश्यक", "प्रमाणीकरण आवश्यक"),
          description: getLocalizedText(
            "Please log in to use emergency services",
            "आपातकालीन सेवाओं का उपयोग करने के लिए लॉग इन करें",
            "आपत्कालीन सेवा वापरण्यासाठी लॉगिन करा"
          ),
          variant: "destructive",
        });
        return;
      }

      // Get user profile for name and phone
      const { data: profile } = await supabase
        .from('profiles')
        .select('full_name, phone_number')
        .eq('id', user.id)
        .single();

      const alertData = {
        alert_id: '', // Will be auto-generated by trigger
        user_id: user.id,
        name: profile?.full_name || 'Anonymous User',
        phone_number: profile?.phone_number || 'Not provided',
        type: contact.type,
        location_name: locationData?.locationName || 'Location not available',
        latitude: locationData?.latitude || null,
        longitude: locationData?.longitude || null,
        message: getLocalizedText(
          `SOS Emergency call placed to ${contact.name}`,
          `${contact.name} को SOS आपातकालीन कॉल किया गया`,
          `${contact.name} ला SOS आपत्कालीन कॉल केला`
        ),
        status: 'Active'
      };

      const { data, error } = await supabase
        .from('emergency_alerts')
        .insert(alertData)
        .select()
        .single();

      if (error) {
        console.error('Error creating SOS alert:', error);
        throw error;
      }

      console.log('SOS Emergency alert created:', data);
      
      toast({
        title: getLocalizedText("SOS Alert Created", "SOS अलर्ट बनाया गया", "SOS अलर्ट तयार केले"),
        description: getLocalizedText(
          `SOS Alert ${data.alert_id} has been sent to authorities`,
          `SOS अलर्ट ${data.alert_id} अधिकारियों को भेजा गया है`,
          `SOS अलर्ट ${data.alert_id} अधिकाऱ्यांना पाठवले आहे`
        ),
      });

    } catch (error) {
      console.error('Error creating SOS emergency alert:', error);
      toast({
        title: getLocalizedText("SOS Alert Error", "SOS अलर्ट त्रुटि", "SOS अलर्ट त्रुटी"),
        description: getLocalizedText(
          "Failed to create SOS emergency alert",
          "SOS आपातकालीन अलर्ट बनाने में विफल",
          "SOS आपत्कालीन अलर्ट तयार करण्यात अयशस्वी"
        ),
        variant: "destructive",
      });
    }
  };

  const handleEmergencyCall = async (phoneNumber: string, contactName: string) => {
    const contact = mockEmergencyContacts.find(c => c.phoneNumber === phoneNumber);
    
    try {
      // Get current location with high accuracy
      const position = await new Promise<GeolocationPosition>((resolve, reject) => {
        navigator.geolocation.getCurrentPosition(resolve, reject, {
          enableHighAccuracy: true,
          timeout: 10000,
          maximumAge: 0
        });
      });

      const { latitude, longitude } = position.coords;
      const locationUrl = `https://maps.google.com/maps?q=${latitude},${longitude}`;
      
      // Create emergency alert in database
      await createEmergencyAlert(contact, {
        latitude,
        longitude,
        locationName: `SOS Location: ${latitude.toFixed(6)}, ${longitude.toFixed(6)}`
      });
      
      // Create emergency SMS with location
      const message = encodeURIComponent(
        getLocalizedText(
          `EMERGENCY ALERT: I need immediate help! My current location: ${locationUrl} - Sent via Pilgrim Safety App`,
          `आपातकालीन अलर्ट: मुझे तत्काल सहायता चाहिए! मेरा वर्तमान स्थान: ${locationUrl} - Pilgrim Safety App से भेजा गया`,
          `आपत्कालीन इशारा: मला तातडीने मदत हवी! माझे सध्याचे स्थान: ${locationUrl} - Pilgrim Safety App द्वारे पाठवले`
        )
      );
      
      const smsUrl = `sms:${phoneNumber}?body=${message}`;
      
      // Send SMS with location first
      window.open(smsUrl, '_blank');
      
      // Show success toast
      toast({
        title: getLocalizedText("Emergency Alert Sent", "आपातकालीन अलर्ट भेजा गया", "आपत्कालीन इशारा पाठवला"),
        description: getLocalizedText(
          `Location shared with ${contactName}. Initiating call...`,
          `${contactName} के साथ स्थान साझा किया गया। कॉल शुरू कर रहे हैं...`,
          `${contactName} सोबत स्थान शेअर केले. कॉल सुरू करत आहे...`
        ),
      });
      
      // Small delay then initiate call
      setTimeout(() => {
        const telUrl = `tel:${phoneNumber}`;
        window.location.href = telUrl;
      }, 2000);
      
    } catch (error) {
      console.error('Location error:', error);
      
      // If location fails, still create alert and make call
      await createEmergencyAlert(contact);
      
      toast({
        title: getLocalizedText("Location Access Failed", "स्थान पहुंच असफल", "स्थान प्रवेश अयशस्वी"),
        description: getLocalizedText(
          "Making emergency call without location. Please share your location manually.",
          "स्थान के बिना आपातकालीन कॉल कर रहे हैं। कृपया अपना स्थान मैन्युअल रूप से साझा करें।",
          "स्थानाशिवाय आपत्कालीन कॉल करत आहे. कृपया तुमचे स्थान मॅन्युअली शेअर करा."
        ),
        variant: "destructive",
      });
      
      // Still make the call
      const telUrl = `tel:${phoneNumber}`;
      window.location.href = telUrl;
    }
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <button className="sos-button animate-pulse-attention">
          <span className="sr-only">Emergency SOS</span>
          <PhoneCall className="w-8 h-8" />
        </button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="text-pilgrim-emergency text-2xl">
            {getLocalizedText("Emergency SOS", "SOS आपातकाल", "SOS आपत्कालीन")}
          </DialogTitle>
          <DialogDescription>
            {getLocalizedText(
              "Select an emergency service to call. Your location will be shared automatically via SMS before the call and an alert will be sent to authorities.",
              "कॉल करने के लिए एक आपातकालीन सेवा चुनें। कॉल से पहले आपका स्थान SMS के माध्यम से स्वचालित रूप से साझा किया जाएगा और अधिकारियों को अलर्ट भेजा जाएगा।",
              "कॉल करण्यासाठी आपत्कालीन सेवा निवडा. कॉल करण्यापूर्वी तुमचे स्थान SMS द्वारे आपोआप शेअर केले जाईल आणि अधिकाऱ्यांना अलर्ट पाठवले जाईल."
            )}
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          {mockEmergencyContacts.map((contact) => (
            <button
              key={contact.id}
              onClick={() => handleEmergencyCall(contact.phoneNumber, contact.name)}
              className="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-red-50 transition-colors"
            >
              <div className={`w-10 h-10 rounded-full flex items-center justify-center ${
                contact.type === 'police' ? 'bg-blue-100 text-blue-700' :
                contact.type === 'ambulance' ? 'bg-red-100 text-red-700' :
                contact.type === 'fire' ? 'bg-orange-100 text-orange-700' :
                contact.type === 'women' ? 'bg-pink-100 text-pink-700' :
                contact.type === 'child' ? 'bg-green-100 text-green-700' :
                'bg-gray-100 text-gray-700'
              }`}>
                {contact.type === 'police' && 
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
                  </svg>
                }
                {contact.type === 'ambulance' && 
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
                  </svg>
                }
                {contact.type === 'fire' && 
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.362 5.214A8.252 8.252 0 0112 21 8.25 8.25 0 016.038 7.048 8.287 8.287 0 009 9.6a8.983 8.983 0 013.361-6.867 8.21 8.21 0 003 2.48z" />
                  </svg>
                }
                {(contact.type === 'women' || contact.type === 'child') && 
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                  </svg>
                }
                {contact.type === 'general' && 
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
                  </svg>
                }
              </div>
              <div className="flex-1 text-left">
                <h3 className="font-medium">{contact.name}</h3>
                <p className="text-sm text-gray-500">{contact.phoneNumber}</p>
              </div>
              <div className="bg-pilgrim-emergency text-white rounded-full p-2">
                <PhoneCall className="w-5 h-5" />
              </div>
            </button>
          ))}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default SosButton;
