// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgtkgajpprutwsqspxlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndGtnYWpwcHJ1dHdzcXNweGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzYzNjYsImV4cCI6MjA2MDcxMjM2Nn0.KLSNgANe4aaLQAsaoa6EL89oO2O_rj8gfO69QsGIAkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});